### ISSUE TITLE
oauth2client.tools.run deprecated: build now fails

### ISSUE THREAD

**Issue by n2ygk** [tienfuc/gdcmdtools#56]
```
gdcmdtools$ python setup.py 
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from gdcmdtools.base import BASE_INFO
  File "/Users/alan/src/gdcmdtools/gdcmdtools/base.py", line 7, in <module>
    from oauth2client.tools import run
ImportError: cannot import name run

gdcmdtools$ pip show oauth2client
---
Name: oauth2client
Version: 1.5.0
Location: /Library/Python/2.7/site-packages
Requires: httplib2, pyasn1, pyasn1-modules, rsa, six
```

See [this post](http://wescpy.blogspot.com/2015/04/migrating-from-toolsrun-to-toolsrunflow.html) which describes changing from tools.run to tools.runflow

**Comment by n2ygk** [comment]
Submitted a pull request: https://github.com/timchen86/gdcmdtools/pull/57
Travis CI build fails because it clones the master branch instead of the pull request.

**Comment by sovcik** [comment]
Same issue here.

**Comment by tienfuc** [comment]
n2ygk,
Thanks, I have fixed this issue with your suggestions, it should be working now.
