### ISSUE TITLE
How to Create a folder, delete a folder, delete files?

### ISSUE THREAD

**Issue by tshrinivasan** [tienfuc/gdcmdtools#67]
How to Create a folder, delete a folder, delete files using gdcmdtools?

Thanks.

**Comment by tienfuc** [comment]
Hi tshrinivasan,
I haven't implemented the features you mentioned, those functions will be available in gdmkdir and gdrm.

**Comment by tshrinivasan** [comment]
Thanks for the info.

Will wait for the features.

Thanks again for your great works.

**Comment by tienfuc** [comment]
gdmkdir is functional in latest source.

**Comment by tshrinivasan** [comment]
You are so awesome.

Thanks for the immediate actions.

**Comment by tienfuc** [comment]
gdrm is available in latest source :)
